#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBongDa")]
	public partial class DataQLBongDaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_BANHUANLUYEN(Tbl_BANHUANLUYEN instance);
    partial void UpdateTbl_BANHUANLUYEN(Tbl_BANHUANLUYEN instance);
    partial void DeleteTbl_BANHUANLUYEN(Tbl_BANHUANLUYEN instance);
    partial void InsertTbl_TRONGTAI(Tbl_TRONGTAI instance);
    partial void UpdateTbl_TRONGTAI(Tbl_TRONGTAI instance);
    partial void DeleteTbl_TRONGTAI(Tbl_TRONGTAI instance);
    partial void InsertTbl_BANTHANG(Tbl_BANTHANG instance);
    partial void UpdateTbl_BANTHANG(Tbl_BANTHANG instance);
    partial void DeleteTbl_BANTHANG(Tbl_BANTHANG instance);
    partial void InsertTbl_BXH(Tbl_BXH instance);
    partial void UpdateTbl_BXH(Tbl_BXH instance);
    partial void DeleteTbl_BXH(Tbl_BXH instance);
    partial void InsertTbl_CAUTHU(Tbl_CAUTHU instance);
    partial void UpdateTbl_CAUTHU(Tbl_CAUTHU instance);
    partial void DeleteTbl_CAUTHU(Tbl_CAUTHU instance);
    partial void InsertTbl_DOIBONG(Tbl_DOIBONG instance);
    partial void UpdateTbl_DOIBONG(Tbl_DOIBONG instance);
    partial void DeleteTbl_DOIBONG(Tbl_DOIBONG instance);
    partial void InsertTbl_KQTHIDAU(Tbl_KQTHIDAU instance);
    partial void UpdateTbl_KQTHIDAU(Tbl_KQTHIDAU instance);
    partial void DeleteTbl_KQTHIDAU(Tbl_KQTHIDAU instance);
    partial void InsertTbl_LICHTHIDAU(Tbl_LICHTHIDAU instance);
    partial void UpdateTbl_LICHTHIDAU(Tbl_LICHTHIDAU instance);
    partial void DeleteTbl_LICHTHIDAU(Tbl_LICHTHIDAU instance);
    partial void InsertTbl_NHATAITRO(Tbl_NHATAITRO instance);
    partial void UpdateTbl_NHATAITRO(Tbl_NHATAITRO instance);
    partial void DeleteTbl_NHATAITRO(Tbl_NHATAITRO instance);
    partial void InsertTbl_SVD(Tbl_SVD instance);
    partial void UpdateTbl_SVD(Tbl_SVD instance);
    partial void DeleteTbl_SVD(Tbl_SVD instance);
    partial void InsertTbl_THEPHAT(Tbl_THEPHAT instance);
    partial void UpdateTbl_THEPHAT(Tbl_THEPHAT instance);
    partial void DeleteTbl_THEPHAT(Tbl_THEPHAT instance);
    #endregion
		
		public DataQLBongDaDataContext() : 
				base(global::DAL.Properties.Settings.Default.tspConnect, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLBongDaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLBongDaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLBongDaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLBongDaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_BANHUANLUYEN> Tbl_BANHUANLUYENs
		{
			get
			{
				return this.GetTable<Tbl_BANHUANLUYEN>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_TRONGTAI> Tbl_TRONGTAIs
		{
			get
			{
				return this.GetTable<Tbl_TRONGTAI>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_BANTHANG> Tbl_BANTHANGs
		{
			get
			{
				return this.GetTable<Tbl_BANTHANG>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_BXH> Tbl_BXHs
		{
			get
			{
				return this.GetTable<Tbl_BXH>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_CAUTHU> Tbl_CAUTHUs
		{
			get
			{
				return this.GetTable<Tbl_CAUTHU>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_DOIBONG> Tbl_DOIBONGs
		{
			get
			{
				return this.GetTable<Tbl_DOIBONG>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_KQTHIDAU> Tbl_KQTHIDAUs
		{
			get
			{
				return this.GetTable<Tbl_KQTHIDAU>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_LICHTHIDAU> Tbl_LICHTHIDAUs
		{
			get
			{
				return this.GetTable<Tbl_LICHTHIDAU>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_NHATAITRO> Tbl_NHATAITROs
		{
			get
			{
				return this.GetTable<Tbl_NHATAITRO>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_SVD> Tbl_SVDs
		{
			get
			{
				return this.GetTable<Tbl_SVD>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_THEPHAT> Tbl_THEPHATs
		{
			get
			{
				return this.GetTable<Tbl_THEPHAT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_BANHUANLUYEN")]
	public partial class Tbl_BANHUANLUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBHL;
		
		private string _TenBHL;
		
		private string _ChucVu;
		
		private string _MaDB;
		
		private EntityRef<Tbl_DOIBONG> _Tbl_DOIBONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBHLChanging(string value);
    partial void OnMaBHLChanged();
    partial void OnTenBHLChanging(string value);
    partial void OnTenBHLChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnMaDBChanging(string value);
    partial void OnMaDBChanged();
    #endregion
		
		public Tbl_BANHUANLUYEN()
		{
			this._Tbl_DOIBONG = default(EntityRef<Tbl_DOIBONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBHL", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBHL
		{
			get
			{
				return this._MaBHL;
			}
			set
			{
				if ((this._MaBHL != value))
				{
					this.OnMaBHLChanging(value);
					this.SendPropertyChanging();
					this._MaBHL = value;
					this.SendPropertyChanged("MaBHL");
					this.OnMaBHLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBHL", DbType="NVarChar(255)")]
		public string TenBHL
		{
			get
			{
				return this._TenBHL;
			}
			set
			{
				if ((this._TenBHL != value))
				{
					this.OnTenBHLChanging(value);
					this.SendPropertyChanging();
					this._TenBHL = value;
					this.SendPropertyChanged("TenBHL");
					this.OnTenBHLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(100)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDB", DbType="NVarChar(10)")]
		public string MaDB
		{
			get
			{
				return this._MaDB;
			}
			set
			{
				if ((this._MaDB != value))
				{
					if (this._Tbl_DOIBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDBChanging(value);
					this.SendPropertyChanging();
					this._MaDB = value;
					this.SendPropertyChanged("MaDB");
					this.OnMaDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_BANHUANLUYEN", Storage="_Tbl_DOIBONG", ThisKey="MaDB", OtherKey="MaDB", IsForeignKey=true)]
		public Tbl_DOIBONG Tbl_DOIBONG
		{
			get
			{
				return this._Tbl_DOIBONG.Entity;
			}
			set
			{
				Tbl_DOIBONG previousValue = this._Tbl_DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_DOIBONG.Entity = null;
						previousValue.Tbl_BANHUANLUYENs.Remove(this);
					}
					this._Tbl_DOIBONG.Entity = value;
					if ((value != null))
					{
						value.Tbl_BANHUANLUYENs.Add(this);
						this._MaDB = value.MaDB;
					}
					else
					{
						this._MaDB = default(string);
					}
					this.SendPropertyChanged("Tbl_DOIBONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_TRONGTAI")]
	public partial class Tbl_TRONGTAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTT;
		
		private string _TenTT;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _QuocTich;
		
		private EntitySet<Tbl_LICHTHIDAU> _Tbl_LICHTHIDAUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(string value);
    partial void OnMaTTChanged();
    partial void OnTenTTChanging(string value);
    partial void OnTenTTChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    #endregion
		
		public Tbl_TRONGTAI()
		{
			this._Tbl_LICHTHIDAUs = new EntitySet<Tbl_LICHTHIDAU>(new Action<Tbl_LICHTHIDAU>(this.attach_Tbl_LICHTHIDAUs), new Action<Tbl_LICHTHIDAU>(this.detach_Tbl_LICHTHIDAUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTT", DbType="NVarChar(255)")]
		public string TenTT
		{
			get
			{
				return this._TenTT;
			}
			set
			{
				if ((this._TenTT != value))
				{
					this.OnTenTTChanging(value);
					this.SendPropertyChanging();
					this._TenTT = value;
					this.SendPropertyChanged("TenTT");
					this.OnTenTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(100)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TRONGTAI_Tbl_LICHTHIDAU", Storage="_Tbl_LICHTHIDAUs", ThisKey="MaTT", OtherKey="MaTT")]
		public EntitySet<Tbl_LICHTHIDAU> Tbl_LICHTHIDAUs
		{
			get
			{
				return this._Tbl_LICHTHIDAUs;
			}
			set
			{
				this._Tbl_LICHTHIDAUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_LICHTHIDAUs(Tbl_LICHTHIDAU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TRONGTAI = this;
		}
		
		private void detach_Tbl_LICHTHIDAUs(Tbl_LICHTHIDAU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TRONGTAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_BANTHANG")]
	public partial class Tbl_BANTHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBT;
		
		private string _MaCT;
		
		private string _LoaiBT;
		
		private System.Nullable<System.TimeSpan> _ThoiDiem;
		
		private string _MaDB;
		
		private string _MaTD;
		
		private EntityRef<Tbl_CAUTHU> _Tbl_CAUTHU;
		
		private EntityRef<Tbl_DOIBONG> _Tbl_DOIBONG;
		
		private EntityRef<Tbl_LICHTHIDAU> _Tbl_LICHTHIDAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBTChanging(string value);
    partial void OnMaBTChanged();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnLoaiBTChanging(string value);
    partial void OnLoaiBTChanged();
    partial void OnThoiDiemChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiDiemChanged();
    partial void OnMaDBChanging(string value);
    partial void OnMaDBChanged();
    partial void OnMaTDChanging(string value);
    partial void OnMaTDChanged();
    #endregion
		
		public Tbl_BANTHANG()
		{
			this._Tbl_CAUTHU = default(EntityRef<Tbl_CAUTHU>);
			this._Tbl_DOIBONG = default(EntityRef<Tbl_DOIBONG>);
			this._Tbl_LICHTHIDAU = default(EntityRef<Tbl_LICHTHIDAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBT", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBT
		{
			get
			{
				return this._MaBT;
			}
			set
			{
				if ((this._MaBT != value))
				{
					this.OnMaBTChanging(value);
					this.SendPropertyChanging();
					this._MaBT = value;
					this.SendPropertyChanged("MaBT");
					this.OnMaBTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(10)")]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					if (this._Tbl_CAUTHU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiBT", DbType="NVarChar(100)")]
		public string LoaiBT
		{
			get
			{
				return this._LoaiBT;
			}
			set
			{
				if ((this._LoaiBT != value))
				{
					this.OnLoaiBTChanging(value);
					this.SendPropertyChanging();
					this._LoaiBT = value;
					this.SendPropertyChanged("LoaiBT");
					this.OnLoaiBTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiem", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiDiem
		{
			get
			{
				return this._ThoiDiem;
			}
			set
			{
				if ((this._ThoiDiem != value))
				{
					this.OnThoiDiemChanging(value);
					this.SendPropertyChanging();
					this._ThoiDiem = value;
					this.SendPropertyChanged("ThoiDiem");
					this.OnThoiDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDB", DbType="NVarChar(10)")]
		public string MaDB
		{
			get
			{
				return this._MaDB;
			}
			set
			{
				if ((this._MaDB != value))
				{
					if (this._Tbl_DOIBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDBChanging(value);
					this.SendPropertyChanging();
					this._MaDB = value;
					this.SendPropertyChanged("MaDB");
					this.OnMaDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTD", DbType="NVarChar(10)")]
		public string MaTD
		{
			get
			{
				return this._MaTD;
			}
			set
			{
				if ((this._MaTD != value))
				{
					if (this._Tbl_LICHTHIDAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTDChanging(value);
					this.SendPropertyChanging();
					this._MaTD = value;
					this.SendPropertyChanged("MaTD");
					this.OnMaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_CAUTHU_Tbl_BANTHANG", Storage="_Tbl_CAUTHU", ThisKey="MaCT", OtherKey="MaCT", IsForeignKey=true)]
		public Tbl_CAUTHU Tbl_CAUTHU
		{
			get
			{
				return this._Tbl_CAUTHU.Entity;
			}
			set
			{
				Tbl_CAUTHU previousValue = this._Tbl_CAUTHU.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_CAUTHU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_CAUTHU.Entity = null;
						previousValue.Tbl_BANTHANGs.Remove(this);
					}
					this._Tbl_CAUTHU.Entity = value;
					if ((value != null))
					{
						value.Tbl_BANTHANGs.Add(this);
						this._MaCT = value.MaCT;
					}
					else
					{
						this._MaCT = default(string);
					}
					this.SendPropertyChanged("Tbl_CAUTHU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_BANTHANG", Storage="_Tbl_DOIBONG", ThisKey="MaDB", OtherKey="MaDB", IsForeignKey=true)]
		public Tbl_DOIBONG Tbl_DOIBONG
		{
			get
			{
				return this._Tbl_DOIBONG.Entity;
			}
			set
			{
				Tbl_DOIBONG previousValue = this._Tbl_DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_DOIBONG.Entity = null;
						previousValue.Tbl_BANTHANGs.Remove(this);
					}
					this._Tbl_DOIBONG.Entity = value;
					if ((value != null))
					{
						value.Tbl_BANTHANGs.Add(this);
						this._MaDB = value.MaDB;
					}
					else
					{
						this._MaDB = default(string);
					}
					this.SendPropertyChanged("Tbl_DOIBONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_LICHTHIDAU_Tbl_BANTHANG", Storage="_Tbl_LICHTHIDAU", ThisKey="MaTD", OtherKey="MaTD", IsForeignKey=true)]
		public Tbl_LICHTHIDAU Tbl_LICHTHIDAU
		{
			get
			{
				return this._Tbl_LICHTHIDAU.Entity;
			}
			set
			{
				Tbl_LICHTHIDAU previousValue = this._Tbl_LICHTHIDAU.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_LICHTHIDAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_LICHTHIDAU.Entity = null;
						previousValue.Tbl_BANTHANGs.Remove(this);
					}
					this._Tbl_LICHTHIDAU.Entity = value;
					if ((value != null))
					{
						value.Tbl_BANTHANGs.Add(this);
						this._MaTD = value.MaTD;
					}
					else
					{
						this._MaTD = default(string);
					}
					this.SendPropertyChanged("Tbl_LICHTHIDAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_BXH")]
	public partial class Tbl_BXH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDB;
		
		private System.Nullable<int> _SoTranThang;
		
		private System.Nullable<int> _SoTranHoa;
		
		private System.Nullable<int> _SoTranThua;
		
		private System.Nullable<int> _SoBanThang;
		
		private System.Nullable<int> _SoBanThua;
		
		private System.Nullable<int> _Diem;
		
		private EntityRef<Tbl_DOIBONG> _Tbl_DOIBONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDBChanging(string value);
    partial void OnMaDBChanged();
    partial void OnSoTranThangChanging(System.Nullable<int> value);
    partial void OnSoTranThangChanged();
    partial void OnSoTranHoaChanging(System.Nullable<int> value);
    partial void OnSoTranHoaChanged();
    partial void OnSoTranThuaChanging(System.Nullable<int> value);
    partial void OnSoTranThuaChanged();
    partial void OnSoBanThangChanging(System.Nullable<int> value);
    partial void OnSoBanThangChanged();
    partial void OnSoBanThuaChanging(System.Nullable<int> value);
    partial void OnSoBanThuaChanged();
    partial void OnDiemChanging(System.Nullable<int> value);
    partial void OnDiemChanged();
    #endregion
		
		public Tbl_BXH()
		{
			this._Tbl_DOIBONG = default(EntityRef<Tbl_DOIBONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDB", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDB
		{
			get
			{
				return this._MaDB;
			}
			set
			{
				if ((this._MaDB != value))
				{
					if (this._Tbl_DOIBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDBChanging(value);
					this.SendPropertyChanging();
					this._MaDB = value;
					this.SendPropertyChanged("MaDB");
					this.OnMaDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTranThang", DbType="Int")]
		public System.Nullable<int> SoTranThang
		{
			get
			{
				return this._SoTranThang;
			}
			set
			{
				if ((this._SoTranThang != value))
				{
					this.OnSoTranThangChanging(value);
					this.SendPropertyChanging();
					this._SoTranThang = value;
					this.SendPropertyChanged("SoTranThang");
					this.OnSoTranThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTranHoa", DbType="Int")]
		public System.Nullable<int> SoTranHoa
		{
			get
			{
				return this._SoTranHoa;
			}
			set
			{
				if ((this._SoTranHoa != value))
				{
					this.OnSoTranHoaChanging(value);
					this.SendPropertyChanging();
					this._SoTranHoa = value;
					this.SendPropertyChanged("SoTranHoa");
					this.OnSoTranHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTranThua", DbType="Int")]
		public System.Nullable<int> SoTranThua
		{
			get
			{
				return this._SoTranThua;
			}
			set
			{
				if ((this._SoTranThua != value))
				{
					this.OnSoTranThuaChanging(value);
					this.SendPropertyChanging();
					this._SoTranThua = value;
					this.SendPropertyChanged("SoTranThua");
					this.OnSoTranThuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBanThang", DbType="Int")]
		public System.Nullable<int> SoBanThang
		{
			get
			{
				return this._SoBanThang;
			}
			set
			{
				if ((this._SoBanThang != value))
				{
					this.OnSoBanThangChanging(value);
					this.SendPropertyChanging();
					this._SoBanThang = value;
					this.SendPropertyChanged("SoBanThang");
					this.OnSoBanThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBanThua", DbType="Int")]
		public System.Nullable<int> SoBanThua
		{
			get
			{
				return this._SoBanThua;
			}
			set
			{
				if ((this._SoBanThua != value))
				{
					this.OnSoBanThuaChanging(value);
					this.SendPropertyChanging();
					this._SoBanThua = value;
					this.SendPropertyChanged("SoBanThua");
					this.OnSoBanThuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Int")]
		public System.Nullable<int> Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this.OnDiemChanging(value);
					this.SendPropertyChanging();
					this._Diem = value;
					this.SendPropertyChanged("Diem");
					this.OnDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_BXH", Storage="_Tbl_DOIBONG", ThisKey="MaDB", OtherKey="MaDB", IsForeignKey=true)]
		public Tbl_DOIBONG Tbl_DOIBONG
		{
			get
			{
				return this._Tbl_DOIBONG.Entity;
			}
			set
			{
				Tbl_DOIBONG previousValue = this._Tbl_DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_DOIBONG.Entity = null;
						previousValue.Tbl_BXH = null;
					}
					this._Tbl_DOIBONG.Entity = value;
					if ((value != null))
					{
						value.Tbl_BXH = this;
						this._MaDB = value.MaDB;
					}
					else
					{
						this._MaDB = default(string);
					}
					this.SendPropertyChanged("Tbl_DOIBONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_CAUTHU")]
	public partial class Tbl_CAUTHU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCT;
		
		private string _TenCT;
		
		private string _ViTri;
		
		private System.Nullable<int> _SoAo;
		
		private string _MaDB;
		
		private EntitySet<Tbl_BANTHANG> _Tbl_BANTHANGs;
		
		private EntitySet<Tbl_THEPHAT> _Tbl_THEPHATs;
		
		private EntityRef<Tbl_DOIBONG> _Tbl_DOIBONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnTenCTChanging(string value);
    partial void OnTenCTChanged();
    partial void OnViTriChanging(string value);
    partial void OnViTriChanged();
    partial void OnSoAoChanging(System.Nullable<int> value);
    partial void OnSoAoChanged();
    partial void OnMaDBChanging(string value);
    partial void OnMaDBChanged();
    #endregion
		
		public Tbl_CAUTHU()
		{
			this._Tbl_BANTHANGs = new EntitySet<Tbl_BANTHANG>(new Action<Tbl_BANTHANG>(this.attach_Tbl_BANTHANGs), new Action<Tbl_BANTHANG>(this.detach_Tbl_BANTHANGs));
			this._Tbl_THEPHATs = new EntitySet<Tbl_THEPHAT>(new Action<Tbl_THEPHAT>(this.attach_Tbl_THEPHATs), new Action<Tbl_THEPHAT>(this.detach_Tbl_THEPHATs));
			this._Tbl_DOIBONG = default(EntityRef<Tbl_DOIBONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCT", DbType="NVarChar(255)")]
		public string TenCT
		{
			get
			{
				return this._TenCT;
			}
			set
			{
				if ((this._TenCT != value))
				{
					this.OnTenCTChanging(value);
					this.SendPropertyChanging();
					this._TenCT = value;
					this.SendPropertyChanged("TenCT");
					this.OnTenCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTri", DbType="NVarChar(100)")]
		public string ViTri
		{
			get
			{
				return this._ViTri;
			}
			set
			{
				if ((this._ViTri != value))
				{
					this.OnViTriChanging(value);
					this.SendPropertyChanging();
					this._ViTri = value;
					this.SendPropertyChanged("ViTri");
					this.OnViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoAo", DbType="Int")]
		public System.Nullable<int> SoAo
		{
			get
			{
				return this._SoAo;
			}
			set
			{
				if ((this._SoAo != value))
				{
					this.OnSoAoChanging(value);
					this.SendPropertyChanging();
					this._SoAo = value;
					this.SendPropertyChanged("SoAo");
					this.OnSoAoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDB", DbType="NVarChar(10)")]
		public string MaDB
		{
			get
			{
				return this._MaDB;
			}
			set
			{
				if ((this._MaDB != value))
				{
					if (this._Tbl_DOIBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDBChanging(value);
					this.SendPropertyChanging();
					this._MaDB = value;
					this.SendPropertyChanged("MaDB");
					this.OnMaDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_CAUTHU_Tbl_BANTHANG", Storage="_Tbl_BANTHANGs", ThisKey="MaCT", OtherKey="MaCT")]
		public EntitySet<Tbl_BANTHANG> Tbl_BANTHANGs
		{
			get
			{
				return this._Tbl_BANTHANGs;
			}
			set
			{
				this._Tbl_BANTHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_CAUTHU_Tbl_THEPHAT", Storage="_Tbl_THEPHATs", ThisKey="MaCT", OtherKey="MaCT")]
		public EntitySet<Tbl_THEPHAT> Tbl_THEPHATs
		{
			get
			{
				return this._Tbl_THEPHATs;
			}
			set
			{
				this._Tbl_THEPHATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_CAUTHU", Storage="_Tbl_DOIBONG", ThisKey="MaDB", OtherKey="MaDB", IsForeignKey=true)]
		public Tbl_DOIBONG Tbl_DOIBONG
		{
			get
			{
				return this._Tbl_DOIBONG.Entity;
			}
			set
			{
				Tbl_DOIBONG previousValue = this._Tbl_DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_DOIBONG.Entity = null;
						previousValue.Tbl_CAUTHUs.Remove(this);
					}
					this._Tbl_DOIBONG.Entity = value;
					if ((value != null))
					{
						value.Tbl_CAUTHUs.Add(this);
						this._MaDB = value.MaDB;
					}
					else
					{
						this._MaDB = default(string);
					}
					this.SendPropertyChanged("Tbl_DOIBONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_BANTHANGs(Tbl_BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_CAUTHU = this;
		}
		
		private void detach_Tbl_BANTHANGs(Tbl_BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_CAUTHU = null;
		}
		
		private void attach_Tbl_THEPHATs(Tbl_THEPHAT entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_CAUTHU = this;
		}
		
		private void detach_Tbl_THEPHATs(Tbl_THEPHAT entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_CAUTHU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_DOIBONG")]
	public partial class Tbl_DOIBONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDB;
		
		private string _TenDB;
		
		private string _DiaChi;
		
		private string _MaNTT;
		
		private EntitySet<Tbl_BANHUANLUYEN> _Tbl_BANHUANLUYENs;
		
		private EntitySet<Tbl_BANTHANG> _Tbl_BANTHANGs;
		
		private EntityRef<Tbl_BXH> _Tbl_BXH;
		
		private EntitySet<Tbl_CAUTHU> _Tbl_CAUTHUs;
		
		private EntitySet<Tbl_LICHTHIDAU> _Tbl_LICHTHIDAUs;
		
		private EntitySet<Tbl_THEPHAT> _Tbl_THEPHATs;
		
		private EntityRef<Tbl_NHATAITRO> _Tbl_NHATAITRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDBChanging(string value);
    partial void OnMaDBChanged();
    partial void OnTenDBChanging(string value);
    partial void OnTenDBChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnMaNTTChanging(string value);
    partial void OnMaNTTChanged();
    #endregion
		
		public Tbl_DOIBONG()
		{
			this._Tbl_BANHUANLUYENs = new EntitySet<Tbl_BANHUANLUYEN>(new Action<Tbl_BANHUANLUYEN>(this.attach_Tbl_BANHUANLUYENs), new Action<Tbl_BANHUANLUYEN>(this.detach_Tbl_BANHUANLUYENs));
			this._Tbl_BANTHANGs = new EntitySet<Tbl_BANTHANG>(new Action<Tbl_BANTHANG>(this.attach_Tbl_BANTHANGs), new Action<Tbl_BANTHANG>(this.detach_Tbl_BANTHANGs));
			this._Tbl_BXH = default(EntityRef<Tbl_BXH>);
			this._Tbl_CAUTHUs = new EntitySet<Tbl_CAUTHU>(new Action<Tbl_CAUTHU>(this.attach_Tbl_CAUTHUs), new Action<Tbl_CAUTHU>(this.detach_Tbl_CAUTHUs));
			this._Tbl_LICHTHIDAUs = new EntitySet<Tbl_LICHTHIDAU>(new Action<Tbl_LICHTHIDAU>(this.attach_Tbl_LICHTHIDAUs), new Action<Tbl_LICHTHIDAU>(this.detach_Tbl_LICHTHIDAUs));
			this._Tbl_THEPHATs = new EntitySet<Tbl_THEPHAT>(new Action<Tbl_THEPHAT>(this.attach_Tbl_THEPHATs), new Action<Tbl_THEPHAT>(this.detach_Tbl_THEPHATs));
			this._Tbl_NHATAITRO = default(EntityRef<Tbl_NHATAITRO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDB", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDB
		{
			get
			{
				return this._MaDB;
			}
			set
			{
				if ((this._MaDB != value))
				{
					this.OnMaDBChanging(value);
					this.SendPropertyChanging();
					this._MaDB = value;
					this.SendPropertyChanged("MaDB");
					this.OnMaDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDB", DbType="NVarChar(255)")]
		public string TenDB
		{
			get
			{
				return this._TenDB;
			}
			set
			{
				if ((this._TenDB != value))
				{
					this.OnTenDBChanging(value);
					this.SendPropertyChanging();
					this._TenDB = value;
					this.SendPropertyChanged("TenDB");
					this.OnTenDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNTT", DbType="NVarChar(10)")]
		public string MaNTT
		{
			get
			{
				return this._MaNTT;
			}
			set
			{
				if ((this._MaNTT != value))
				{
					if (this._Tbl_NHATAITRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNTTChanging(value);
					this.SendPropertyChanging();
					this._MaNTT = value;
					this.SendPropertyChanged("MaNTT");
					this.OnMaNTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_BANHUANLUYEN", Storage="_Tbl_BANHUANLUYENs", ThisKey="MaDB", OtherKey="MaDB")]
		public EntitySet<Tbl_BANHUANLUYEN> Tbl_BANHUANLUYENs
		{
			get
			{
				return this._Tbl_BANHUANLUYENs;
			}
			set
			{
				this._Tbl_BANHUANLUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_BANTHANG", Storage="_Tbl_BANTHANGs", ThisKey="MaDB", OtherKey="MaDB")]
		public EntitySet<Tbl_BANTHANG> Tbl_BANTHANGs
		{
			get
			{
				return this._Tbl_BANTHANGs;
			}
			set
			{
				this._Tbl_BANTHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_BXH", Storage="_Tbl_BXH", ThisKey="MaDB", OtherKey="MaDB", IsUnique=true, IsForeignKey=false)]
		public Tbl_BXH Tbl_BXH
		{
			get
			{
				return this._Tbl_BXH.Entity;
			}
			set
			{
				Tbl_BXH previousValue = this._Tbl_BXH.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_BXH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_BXH.Entity = null;
						previousValue.Tbl_DOIBONG = null;
					}
					this._Tbl_BXH.Entity = value;
					if ((value != null))
					{
						value.Tbl_DOIBONG = this;
					}
					this.SendPropertyChanged("Tbl_BXH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_CAUTHU", Storage="_Tbl_CAUTHUs", ThisKey="MaDB", OtherKey="MaDB")]
		public EntitySet<Tbl_CAUTHU> Tbl_CAUTHUs
		{
			get
			{
				return this._Tbl_CAUTHUs;
			}
			set
			{
				this._Tbl_CAUTHUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_LICHTHIDAU", Storage="_Tbl_LICHTHIDAUs", ThisKey="MaDB", OtherKey="MaDB")]
		public EntitySet<Tbl_LICHTHIDAU> Tbl_LICHTHIDAUs
		{
			get
			{
				return this._Tbl_LICHTHIDAUs;
			}
			set
			{
				this._Tbl_LICHTHIDAUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_THEPHAT", Storage="_Tbl_THEPHATs", ThisKey="MaDB", OtherKey="MaDB")]
		public EntitySet<Tbl_THEPHAT> Tbl_THEPHATs
		{
			get
			{
				return this._Tbl_THEPHATs;
			}
			set
			{
				this._Tbl_THEPHATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_NHATAITRO_Tbl_DOIBONG", Storage="_Tbl_NHATAITRO", ThisKey="MaNTT", OtherKey="MaNTT", IsForeignKey=true)]
		public Tbl_NHATAITRO Tbl_NHATAITRO
		{
			get
			{
				return this._Tbl_NHATAITRO.Entity;
			}
			set
			{
				Tbl_NHATAITRO previousValue = this._Tbl_NHATAITRO.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_NHATAITRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_NHATAITRO.Entity = null;
						previousValue.Tbl_DOIBONGs.Remove(this);
					}
					this._Tbl_NHATAITRO.Entity = value;
					if ((value != null))
					{
						value.Tbl_DOIBONGs.Add(this);
						this._MaNTT = value.MaNTT;
					}
					else
					{
						this._MaNTT = default(string);
					}
					this.SendPropertyChanged("Tbl_NHATAITRO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_BANHUANLUYENs(Tbl_BANHUANLUYEN entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = this;
		}
		
		private void detach_Tbl_BANHUANLUYENs(Tbl_BANHUANLUYEN entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = null;
		}
		
		private void attach_Tbl_BANTHANGs(Tbl_BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = this;
		}
		
		private void detach_Tbl_BANTHANGs(Tbl_BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = null;
		}
		
		private void attach_Tbl_CAUTHUs(Tbl_CAUTHU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = this;
		}
		
		private void detach_Tbl_CAUTHUs(Tbl_CAUTHU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = null;
		}
		
		private void attach_Tbl_LICHTHIDAUs(Tbl_LICHTHIDAU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = this;
		}
		
		private void detach_Tbl_LICHTHIDAUs(Tbl_LICHTHIDAU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = null;
		}
		
		private void attach_Tbl_THEPHATs(Tbl_THEPHAT entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = this;
		}
		
		private void detach_Tbl_THEPHATs(Tbl_THEPHAT entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DOIBONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_KQTHIDAU")]
	public partial class Tbl_KQTHIDAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKQ;
		
		private string _MaTD;
		
		private string _Doi1;
		
		private string _Doi2;
		
		private int _SoThePhatDoi1;
		
		private int _SoThePhatDoi2;
		
		private int _SoBTDoi1;
		
		private int _SoBTDoi2;
		
		private EntityRef<Tbl_LICHTHIDAU> _Tbl_LICHTHIDAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKQChanging(string value);
    partial void OnMaKQChanged();
    partial void OnMaTDChanging(string value);
    partial void OnMaTDChanged();
    partial void OnDoi1Changing(string value);
    partial void OnDoi1Changed();
    partial void OnDoi2Changing(string value);
    partial void OnDoi2Changed();
    partial void OnSoThePhatDoi1Changing(int value);
    partial void OnSoThePhatDoi1Changed();
    partial void OnSoThePhatDoi2Changing(int value);
    partial void OnSoThePhatDoi2Changed();
    partial void OnSoBTDoi1Changing(int value);
    partial void OnSoBTDoi1Changed();
    partial void OnSoBTDoi2Changing(int value);
    partial void OnSoBTDoi2Changed();
    #endregion
		
		public Tbl_KQTHIDAU()
		{
			this._Tbl_LICHTHIDAU = default(EntityRef<Tbl_LICHTHIDAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKQ", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKQ
		{
			get
			{
				return this._MaKQ;
			}
			set
			{
				if ((this._MaKQ != value))
				{
					this.OnMaKQChanging(value);
					this.SendPropertyChanging();
					this._MaKQ = value;
					this.SendPropertyChanged("MaKQ");
					this.OnMaKQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTD", DbType="NVarChar(10)")]
		public string MaTD
		{
			get
			{
				return this._MaTD;
			}
			set
			{
				if ((this._MaTD != value))
				{
					if (this._Tbl_LICHTHIDAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTDChanging(value);
					this.SendPropertyChanging();
					this._MaTD = value;
					this.SendPropertyChanged("MaTD");
					this.OnMaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doi1", DbType="NVarChar(255)")]
		public string Doi1
		{
			get
			{
				return this._Doi1;
			}
			set
			{
				if ((this._Doi1 != value))
				{
					this.OnDoi1Changing(value);
					this.SendPropertyChanging();
					this._Doi1 = value;
					this.SendPropertyChanged("Doi1");
					this.OnDoi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doi2", DbType="NVarChar(255)")]
		public string Doi2
		{
			get
			{
				return this._Doi2;
			}
			set
			{
				if ((this._Doi2 != value))
				{
					this.OnDoi2Changing(value);
					this.SendPropertyChanging();
					this._Doi2 = value;
					this.SendPropertyChanged("Doi2");
					this.OnDoi2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThePhatDoi1", DbType="Int NOT NULL")]
		public int SoThePhatDoi1
		{
			get
			{
				return this._SoThePhatDoi1;
			}
			set
			{
				if ((this._SoThePhatDoi1 != value))
				{
					this.OnSoThePhatDoi1Changing(value);
					this.SendPropertyChanging();
					this._SoThePhatDoi1 = value;
					this.SendPropertyChanged("SoThePhatDoi1");
					this.OnSoThePhatDoi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThePhatDoi2", DbType="Int NOT NULL")]
		public int SoThePhatDoi2
		{
			get
			{
				return this._SoThePhatDoi2;
			}
			set
			{
				if ((this._SoThePhatDoi2 != value))
				{
					this.OnSoThePhatDoi2Changing(value);
					this.SendPropertyChanging();
					this._SoThePhatDoi2 = value;
					this.SendPropertyChanged("SoThePhatDoi2");
					this.OnSoThePhatDoi2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBTDoi1", DbType="Int NOT NULL")]
		public int SoBTDoi1
		{
			get
			{
				return this._SoBTDoi1;
			}
			set
			{
				if ((this._SoBTDoi1 != value))
				{
					this.OnSoBTDoi1Changing(value);
					this.SendPropertyChanging();
					this._SoBTDoi1 = value;
					this.SendPropertyChanged("SoBTDoi1");
					this.OnSoBTDoi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBTDoi2", DbType="Int NOT NULL")]
		public int SoBTDoi2
		{
			get
			{
				return this._SoBTDoi2;
			}
			set
			{
				if ((this._SoBTDoi2 != value))
				{
					this.OnSoBTDoi2Changing(value);
					this.SendPropertyChanging();
					this._SoBTDoi2 = value;
					this.SendPropertyChanged("SoBTDoi2");
					this.OnSoBTDoi2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_LICHTHIDAU_Tbl_KQTHIDAU", Storage="_Tbl_LICHTHIDAU", ThisKey="MaTD", OtherKey="MaTD", IsForeignKey=true)]
		public Tbl_LICHTHIDAU Tbl_LICHTHIDAU
		{
			get
			{
				return this._Tbl_LICHTHIDAU.Entity;
			}
			set
			{
				Tbl_LICHTHIDAU previousValue = this._Tbl_LICHTHIDAU.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_LICHTHIDAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_LICHTHIDAU.Entity = null;
						previousValue.Tbl_KQTHIDAUs.Remove(this);
					}
					this._Tbl_LICHTHIDAU.Entity = value;
					if ((value != null))
					{
						value.Tbl_KQTHIDAUs.Add(this);
						this._MaTD = value.MaTD;
					}
					else
					{
						this._MaTD = default(string);
					}
					this.SendPropertyChanged("Tbl_LICHTHIDAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_LICHTHIDAU")]
	public partial class Tbl_LICHTHIDAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTD;
		
		private string _MaDB;
		
		private string _MaSVD;
		
		private string _MaTT;
		
		private string _Doi1;
		
		private string _Doi2;
		
		private System.Nullable<System.DateTime> _NgayThiDau;
		
		private System.TimeSpan _GioTD;
		
		private EntitySet<Tbl_BANTHANG> _Tbl_BANTHANGs;
		
		private EntitySet<Tbl_KQTHIDAU> _Tbl_KQTHIDAUs;
		
		private EntitySet<Tbl_THEPHAT> _Tbl_THEPHATs;
		
		private EntityRef<Tbl_DOIBONG> _Tbl_DOIBONG;
		
		private EntityRef<Tbl_TRONGTAI> _Tbl_TRONGTAI;
		
		private EntityRef<Tbl_SVD> _Tbl_SVD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTDChanging(string value);
    partial void OnMaTDChanged();
    partial void OnMaDBChanging(string value);
    partial void OnMaDBChanged();
    partial void OnMaSVDChanging(string value);
    partial void OnMaSVDChanged();
    partial void OnMaTTChanging(string value);
    partial void OnMaTTChanged();
    partial void OnDoi1Changing(string value);
    partial void OnDoi1Changed();
    partial void OnDoi2Changing(string value);
    partial void OnDoi2Changed();
    partial void OnNgayThiDauChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThiDauChanged();
    partial void OnGioTDChanging(System.TimeSpan value);
    partial void OnGioTDChanged();
    #endregion
		
		public Tbl_LICHTHIDAU()
		{
			this._Tbl_BANTHANGs = new EntitySet<Tbl_BANTHANG>(new Action<Tbl_BANTHANG>(this.attach_Tbl_BANTHANGs), new Action<Tbl_BANTHANG>(this.detach_Tbl_BANTHANGs));
			this._Tbl_KQTHIDAUs = new EntitySet<Tbl_KQTHIDAU>(new Action<Tbl_KQTHIDAU>(this.attach_Tbl_KQTHIDAUs), new Action<Tbl_KQTHIDAU>(this.detach_Tbl_KQTHIDAUs));
			this._Tbl_THEPHATs = new EntitySet<Tbl_THEPHAT>(new Action<Tbl_THEPHAT>(this.attach_Tbl_THEPHATs), new Action<Tbl_THEPHAT>(this.detach_Tbl_THEPHATs));
			this._Tbl_DOIBONG = default(EntityRef<Tbl_DOIBONG>);
			this._Tbl_TRONGTAI = default(EntityRef<Tbl_TRONGTAI>);
			this._Tbl_SVD = default(EntityRef<Tbl_SVD>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTD", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTD
		{
			get
			{
				return this._MaTD;
			}
			set
			{
				if ((this._MaTD != value))
				{
					this.OnMaTDChanging(value);
					this.SendPropertyChanging();
					this._MaTD = value;
					this.SendPropertyChanged("MaTD");
					this.OnMaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDB", DbType="NVarChar(10)")]
		public string MaDB
		{
			get
			{
				return this._MaDB;
			}
			set
			{
				if ((this._MaDB != value))
				{
					if (this._Tbl_DOIBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDBChanging(value);
					this.SendPropertyChanging();
					this._MaDB = value;
					this.SendPropertyChanged("MaDB");
					this.OnMaDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSVD", DbType="NVarChar(10)")]
		public string MaSVD
		{
			get
			{
				return this._MaSVD;
			}
			set
			{
				if ((this._MaSVD != value))
				{
					if (this._Tbl_SVD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVDChanging(value);
					this.SendPropertyChanging();
					this._MaSVD = value;
					this.SendPropertyChanged("MaSVD");
					this.OnMaSVDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="NVarChar(10)")]
		public string MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					if (this._Tbl_TRONGTAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doi1", DbType="NVarChar(255)")]
		public string Doi1
		{
			get
			{
				return this._Doi1;
			}
			set
			{
				if ((this._Doi1 != value))
				{
					this.OnDoi1Changing(value);
					this.SendPropertyChanging();
					this._Doi1 = value;
					this.SendPropertyChanged("Doi1");
					this.OnDoi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doi2", DbType="NVarChar(255)")]
		public string Doi2
		{
			get
			{
				return this._Doi2;
			}
			set
			{
				if ((this._Doi2 != value))
				{
					this.OnDoi2Changing(value);
					this.SendPropertyChanging();
					this._Doi2 = value;
					this.SendPropertyChanged("Doi2");
					this.OnDoi2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThiDau", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThiDau
		{
			get
			{
				return this._NgayThiDau;
			}
			set
			{
				if ((this._NgayThiDau != value))
				{
					this.OnNgayThiDauChanging(value);
					this.SendPropertyChanging();
					this._NgayThiDau = value;
					this.SendPropertyChanged("NgayThiDau");
					this.OnNgayThiDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioTD", DbType="Time NOT NULL")]
		public System.TimeSpan GioTD
		{
			get
			{
				return this._GioTD;
			}
			set
			{
				if ((this._GioTD != value))
				{
					this.OnGioTDChanging(value);
					this.SendPropertyChanging();
					this._GioTD = value;
					this.SendPropertyChanged("GioTD");
					this.OnGioTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_LICHTHIDAU_Tbl_BANTHANG", Storage="_Tbl_BANTHANGs", ThisKey="MaTD", OtherKey="MaTD")]
		public EntitySet<Tbl_BANTHANG> Tbl_BANTHANGs
		{
			get
			{
				return this._Tbl_BANTHANGs;
			}
			set
			{
				this._Tbl_BANTHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_LICHTHIDAU_Tbl_KQTHIDAU", Storage="_Tbl_KQTHIDAUs", ThisKey="MaTD", OtherKey="MaTD")]
		public EntitySet<Tbl_KQTHIDAU> Tbl_KQTHIDAUs
		{
			get
			{
				return this._Tbl_KQTHIDAUs;
			}
			set
			{
				this._Tbl_KQTHIDAUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_LICHTHIDAU_Tbl_THEPHAT", Storage="_Tbl_THEPHATs", ThisKey="MaTD", OtherKey="MaTD")]
		public EntitySet<Tbl_THEPHAT> Tbl_THEPHATs
		{
			get
			{
				return this._Tbl_THEPHATs;
			}
			set
			{
				this._Tbl_THEPHATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_LICHTHIDAU", Storage="_Tbl_DOIBONG", ThisKey="MaDB", OtherKey="MaDB", IsForeignKey=true)]
		public Tbl_DOIBONG Tbl_DOIBONG
		{
			get
			{
				return this._Tbl_DOIBONG.Entity;
			}
			set
			{
				Tbl_DOIBONG previousValue = this._Tbl_DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_DOIBONG.Entity = null;
						previousValue.Tbl_LICHTHIDAUs.Remove(this);
					}
					this._Tbl_DOIBONG.Entity = value;
					if ((value != null))
					{
						value.Tbl_LICHTHIDAUs.Add(this);
						this._MaDB = value.MaDB;
					}
					else
					{
						this._MaDB = default(string);
					}
					this.SendPropertyChanged("Tbl_DOIBONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TRONGTAI_Tbl_LICHTHIDAU", Storage="_Tbl_TRONGTAI", ThisKey="MaTT", OtherKey="MaTT", IsForeignKey=true)]
		public Tbl_TRONGTAI Tbl_TRONGTAI
		{
			get
			{
				return this._Tbl_TRONGTAI.Entity;
			}
			set
			{
				Tbl_TRONGTAI previousValue = this._Tbl_TRONGTAI.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_TRONGTAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_TRONGTAI.Entity = null;
						previousValue.Tbl_LICHTHIDAUs.Remove(this);
					}
					this._Tbl_TRONGTAI.Entity = value;
					if ((value != null))
					{
						value.Tbl_LICHTHIDAUs.Add(this);
						this._MaTT = value.MaTT;
					}
					else
					{
						this._MaTT = default(string);
					}
					this.SendPropertyChanged("Tbl_TRONGTAI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_SVD_Tbl_LICHTHIDAU", Storage="_Tbl_SVD", ThisKey="MaSVD", OtherKey="MaSVD", IsForeignKey=true)]
		public Tbl_SVD Tbl_SVD
		{
			get
			{
				return this._Tbl_SVD.Entity;
			}
			set
			{
				Tbl_SVD previousValue = this._Tbl_SVD.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_SVD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_SVD.Entity = null;
						previousValue.Tbl_LICHTHIDAUs.Remove(this);
					}
					this._Tbl_SVD.Entity = value;
					if ((value != null))
					{
						value.Tbl_LICHTHIDAUs.Add(this);
						this._MaSVD = value.MaSVD;
					}
					else
					{
						this._MaSVD = default(string);
					}
					this.SendPropertyChanged("Tbl_SVD");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_BANTHANGs(Tbl_BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_LICHTHIDAU = this;
		}
		
		private void detach_Tbl_BANTHANGs(Tbl_BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_LICHTHIDAU = null;
		}
		
		private void attach_Tbl_KQTHIDAUs(Tbl_KQTHIDAU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_LICHTHIDAU = this;
		}
		
		private void detach_Tbl_KQTHIDAUs(Tbl_KQTHIDAU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_LICHTHIDAU = null;
		}
		
		private void attach_Tbl_THEPHATs(Tbl_THEPHAT entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_LICHTHIDAU = this;
		}
		
		private void detach_Tbl_THEPHATs(Tbl_THEPHAT entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_LICHTHIDAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_NHATAITRO")]
	public partial class Tbl_NHATAITRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNTT;
		
		private string _TenNTT;
		
		private System.Nullable<int> _SDT;
		
		private EntitySet<Tbl_DOIBONG> _Tbl_DOIBONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNTTChanging(string value);
    partial void OnMaNTTChanged();
    partial void OnTenNTTChanging(string value);
    partial void OnTenNTTChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    #endregion
		
		public Tbl_NHATAITRO()
		{
			this._Tbl_DOIBONGs = new EntitySet<Tbl_DOIBONG>(new Action<Tbl_DOIBONG>(this.attach_Tbl_DOIBONGs), new Action<Tbl_DOIBONG>(this.detach_Tbl_DOIBONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNTT", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNTT
		{
			get
			{
				return this._MaNTT;
			}
			set
			{
				if ((this._MaNTT != value))
				{
					this.OnMaNTTChanging(value);
					this.SendPropertyChanging();
					this._MaNTT = value;
					this.SendPropertyChanged("MaNTT");
					this.OnMaNTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNTT", DbType="NVarChar(255)")]
		public string TenNTT
		{
			get
			{
				return this._TenNTT;
			}
			set
			{
				if ((this._TenNTT != value))
				{
					this.OnTenNTTChanging(value);
					this.SendPropertyChanging();
					this._TenNTT = value;
					this.SendPropertyChanged("TenNTT");
					this.OnTenNTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_NHATAITRO_Tbl_DOIBONG", Storage="_Tbl_DOIBONGs", ThisKey="MaNTT", OtherKey="MaNTT")]
		public EntitySet<Tbl_DOIBONG> Tbl_DOIBONGs
		{
			get
			{
				return this._Tbl_DOIBONGs;
			}
			set
			{
				this._Tbl_DOIBONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_DOIBONGs(Tbl_DOIBONG entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_NHATAITRO = this;
		}
		
		private void detach_Tbl_DOIBONGs(Tbl_DOIBONG entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_NHATAITRO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_SVD")]
	public partial class Tbl_SVD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSVD;
		
		private string _TenSVD;
		
		private System.Nullable<int> _SucChua;
		
		private string _DiaChi;
		
		private EntitySet<Tbl_LICHTHIDAU> _Tbl_LICHTHIDAUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVDChanging(string value);
    partial void OnMaSVDChanged();
    partial void OnTenSVDChanging(string value);
    partial void OnTenSVDChanged();
    partial void OnSucChuaChanging(System.Nullable<int> value);
    partial void OnSucChuaChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public Tbl_SVD()
		{
			this._Tbl_LICHTHIDAUs = new EntitySet<Tbl_LICHTHIDAU>(new Action<Tbl_LICHTHIDAU>(this.attach_Tbl_LICHTHIDAUs), new Action<Tbl_LICHTHIDAU>(this.detach_Tbl_LICHTHIDAUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSVD", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSVD
		{
			get
			{
				return this._MaSVD;
			}
			set
			{
				if ((this._MaSVD != value))
				{
					this.OnMaSVDChanging(value);
					this.SendPropertyChanging();
					this._MaSVD = value;
					this.SendPropertyChanged("MaSVD");
					this.OnMaSVDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSVD", DbType="NVarChar(100)")]
		public string TenSVD
		{
			get
			{
				return this._TenSVD;
			}
			set
			{
				if ((this._TenSVD != value))
				{
					this.OnTenSVDChanging(value);
					this.SendPropertyChanging();
					this._TenSVD = value;
					this.SendPropertyChanged("TenSVD");
					this.OnTenSVDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChua", DbType="Int")]
		public System.Nullable<int> SucChua
		{
			get
			{
				return this._SucChua;
			}
			set
			{
				if ((this._SucChua != value))
				{
					this.OnSucChuaChanging(value);
					this.SendPropertyChanging();
					this._SucChua = value;
					this.SendPropertyChanged("SucChua");
					this.OnSucChuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_SVD_Tbl_LICHTHIDAU", Storage="_Tbl_LICHTHIDAUs", ThisKey="MaSVD", OtherKey="MaSVD")]
		public EntitySet<Tbl_LICHTHIDAU> Tbl_LICHTHIDAUs
		{
			get
			{
				return this._Tbl_LICHTHIDAUs;
			}
			set
			{
				this._Tbl_LICHTHIDAUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_LICHTHIDAUs(Tbl_LICHTHIDAU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_SVD = this;
		}
		
		private void detach_Tbl_LICHTHIDAUs(Tbl_LICHTHIDAU entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_SVD = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_THEPHAT")]
	public partial class Tbl_THEPHAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTP;
		
		private string _TenTP;
		
		private System.Nullable<System.TimeSpan> _ThoiDiem;
		
		private string _MaCT;
		
		private string _MaDB;
		
		private string _MaTD;
		
		private EntityRef<Tbl_CAUTHU> _Tbl_CAUTHU;
		
		private EntityRef<Tbl_DOIBONG> _Tbl_DOIBONG;
		
		private EntityRef<Tbl_LICHTHIDAU> _Tbl_LICHTHIDAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTPChanging(string value);
    partial void OnMaTPChanged();
    partial void OnTenTPChanging(string value);
    partial void OnTenTPChanged();
    partial void OnThoiDiemChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiDiemChanged();
    partial void OnMaCTChanging(string value);
    partial void OnMaCTChanged();
    partial void OnMaDBChanging(string value);
    partial void OnMaDBChanged();
    partial void OnMaTDChanging(string value);
    partial void OnMaTDChanged();
    #endregion
		
		public Tbl_THEPHAT()
		{
			this._Tbl_CAUTHU = default(EntityRef<Tbl_CAUTHU>);
			this._Tbl_DOIBONG = default(EntityRef<Tbl_DOIBONG>);
			this._Tbl_LICHTHIDAU = default(EntityRef<Tbl_LICHTHIDAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					this.OnMaTPChanging(value);
					this.SendPropertyChanging();
					this._MaTP = value;
					this.SendPropertyChanged("MaTP");
					this.OnMaTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTP", DbType="NVarChar(100)")]
		public string TenTP
		{
			get
			{
				return this._TenTP;
			}
			set
			{
				if ((this._TenTP != value))
				{
					this.OnTenTPChanging(value);
					this.SendPropertyChanging();
					this._TenTP = value;
					this.SendPropertyChanged("TenTP");
					this.OnTenTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiem", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiDiem
		{
			get
			{
				return this._ThoiDiem;
			}
			set
			{
				if ((this._ThoiDiem != value))
				{
					this.OnThoiDiemChanging(value);
					this.SendPropertyChanging();
					this._ThoiDiem = value;
					this.SendPropertyChanged("ThoiDiem");
					this.OnThoiDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(10)")]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					if (this._Tbl_CAUTHU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCTChanging(value);
					this.SendPropertyChanging();
					this._MaCT = value;
					this.SendPropertyChanged("MaCT");
					this.OnMaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDB", DbType="NVarChar(10)")]
		public string MaDB
		{
			get
			{
				return this._MaDB;
			}
			set
			{
				if ((this._MaDB != value))
				{
					if (this._Tbl_DOIBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDBChanging(value);
					this.SendPropertyChanging();
					this._MaDB = value;
					this.SendPropertyChanged("MaDB");
					this.OnMaDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTD", DbType="NVarChar(10)")]
		public string MaTD
		{
			get
			{
				return this._MaTD;
			}
			set
			{
				if ((this._MaTD != value))
				{
					if (this._Tbl_LICHTHIDAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTDChanging(value);
					this.SendPropertyChanging();
					this._MaTD = value;
					this.SendPropertyChanged("MaTD");
					this.OnMaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_CAUTHU_Tbl_THEPHAT", Storage="_Tbl_CAUTHU", ThisKey="MaCT", OtherKey="MaCT", IsForeignKey=true)]
		public Tbl_CAUTHU Tbl_CAUTHU
		{
			get
			{
				return this._Tbl_CAUTHU.Entity;
			}
			set
			{
				Tbl_CAUTHU previousValue = this._Tbl_CAUTHU.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_CAUTHU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_CAUTHU.Entity = null;
						previousValue.Tbl_THEPHATs.Remove(this);
					}
					this._Tbl_CAUTHU.Entity = value;
					if ((value != null))
					{
						value.Tbl_THEPHATs.Add(this);
						this._MaCT = value.MaCT;
					}
					else
					{
						this._MaCT = default(string);
					}
					this.SendPropertyChanged("Tbl_CAUTHU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DOIBONG_Tbl_THEPHAT", Storage="_Tbl_DOIBONG", ThisKey="MaDB", OtherKey="MaDB", IsForeignKey=true)]
		public Tbl_DOIBONG Tbl_DOIBONG
		{
			get
			{
				return this._Tbl_DOIBONG.Entity;
			}
			set
			{
				Tbl_DOIBONG previousValue = this._Tbl_DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_DOIBONG.Entity = null;
						previousValue.Tbl_THEPHATs.Remove(this);
					}
					this._Tbl_DOIBONG.Entity = value;
					if ((value != null))
					{
						value.Tbl_THEPHATs.Add(this);
						this._MaDB = value.MaDB;
					}
					else
					{
						this._MaDB = default(string);
					}
					this.SendPropertyChanged("Tbl_DOIBONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_LICHTHIDAU_Tbl_THEPHAT", Storage="_Tbl_LICHTHIDAU", ThisKey="MaTD", OtherKey="MaTD", IsForeignKey=true)]
		public Tbl_LICHTHIDAU Tbl_LICHTHIDAU
		{
			get
			{
				return this._Tbl_LICHTHIDAU.Entity;
			}
			set
			{
				Tbl_LICHTHIDAU previousValue = this._Tbl_LICHTHIDAU.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_LICHTHIDAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_LICHTHIDAU.Entity = null;
						previousValue.Tbl_THEPHATs.Remove(this);
					}
					this._Tbl_LICHTHIDAU.Entity = value;
					if ((value != null))
					{
						value.Tbl_THEPHATs.Add(this);
						this._MaTD = value.MaTD;
					}
					else
					{
						this._MaTD = default(string);
					}
					this.SendPropertyChanged("Tbl_LICHTHIDAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
